---
title: Escribiendo datos a un archivo con Python
hero_image: images/banner.png
description: Escribir datos a un archivo
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
site_areas:
steps:
  - 
    title: Escribiendo a un archivo
