---
title: Writing data to a file with Python
hero_image: images/banner.png
description: Write data to a file
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
site_areas:
steps:
  - 
    title: Writing to a file
